apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - namespace.yaml
  - ../../base

images:
  - name: event-driven-ecommerce/api-gateway
    newTag: staging
  - name: event-driven-ecommerce/ms-user
    newTag: staging
  - name: event-driven-ecommerce/ms-product
    newTag: staging
  - name: event-driven-ecommerce/ms-order
    newTag: staging
  - name: event-driven-ecommerce/ms-inventory
    newTag: staging
  - name: event-driven-ecommerce/ms-analytics
    newTag: staging
  - name: event-driven-ecommerce/admin
    newTag: staging
  - name: event-driven-ecommerce/frontend
    newTag: staging