apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - namespace.yaml
  - ../../base

namePrefix: staging-

images:
  - name: micro-services/api-gateway
    newTag: staging
  - name: micro-services/ms-user
    newTag: staging
  - name: micro-services/ms-product
    newTag: staging
  - name: micro-services/ms-order
    newTag: staging
  - name: micro-services/frontend
    newTag: staging