apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
data:
  NODE_ENV: "production"
  PORT_GATEWAY: "5460"
  PORT_USER: "5463"
  PORT_PRODUCT: "5464"
  PORT_ORDER: "5465"
  PORT_FRONTEND: "5462"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USERNAME: "postgres"
  DB_DATABASE: "ecommerce"
  MONGODB_URI: "mongodb://admin:password@mongodb:27017/ecommerce?authSource=admin"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  BULLMQ_CONCURRENCY: "5"
  BULLMQ_PREFIX: "ecommerce"
  ELASTICSEARCH_HOST: "http://elasticsearch:9200"
  USER_SERVICE_URL: "http://ms-user:5463"
  PRODUCT_SERVICE_URL: "http://ms-product:5464"
  ORDER_SERVICE_URL: "http://ms-order:5465"
  NEXT_PUBLIC_API_URL: "http://api.ecommerce.local"