apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  rules:
    - host: ecommerce.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 5460
          - path: /api-docs
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 5460
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 5462