apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secrets.yaml
  - ingress.yaml
  - api-gateway.yaml
  - ms-user.yaml
  - ms-product.yaml
  - ms-order.yaml
  - frontend.yaml
  - postgres.yaml
  - mongodb.yaml
  - redis.yaml
  - elasticsearch.yaml