export interface SeedOrder {
  id: string
  orderNumber: string
  userId: string
  customerName: string
  customerEmail: string
  status: 'PENDING' | 'CONFIRMED' | 'PROCESSING' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED'
  subtotal: number
  taxAmount: number
  shippingAmount: number
  discountAmount: number
  totalAmount: number
  currency: string
  paymentMethod: 'STRIPE' | 'PAYPAL' | 'MOCK'
  paymentStatus: 'PAID' | 'PENDING' | 'FAILED' | 'REFUNDED'
  transactionId: string
  shippingAddress: {
    addressLine1: string
    city: string
    state: string
    postalCode: string
    country: string
  }
  items: {
    productId: string
    sku: string
    title: string
    unitPrice: number
    quantity: number
    totalPrice: number
    imageUrl?: string
  }[]
  createdAt: string
  updatedAt: string
}

const day = 86400000
const hour = 3600000

export const SEED_ORDERS: SeedOrder[] = [
  {
    id: 'order-1',
    orderNumber: 'ORD-100201',
    userId: 'user-customer-01',
    customerName: 'Alex Morgan',
    customerEmail: 'customer@ecommerce.com',
    status: 'DELIVERED',
    subtotal: 349.99,
    taxAmount: 28.0,
    shippingAmount: 0,
    discountAmount: 0,
    totalAmount: 377.99,
    currency: 'USD',
    paymentMethod: 'STRIPE',
    paymentStatus: 'PAID',
    transactionId: 'ch_3NrkX2LkdIwHu7ix08wFp101',
    shippingAddress: {
      addressLine1: '742 Evergreen Terrace',
      city: 'Springfield',
      state: 'OR',
      postalCode: '97477',
      country: 'United States',
    },
    items: [
      {
        productId: 'prod-1',
        sku: 'AUDIO-AURA-01',
        title: 'Aura Pro Wireless ANC Headphones',
        unitPrice: 349.99,
        quantity: 1,
        totalPrice: 349.99,
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
      },
    ],
    createdAt: new Date(Date.now() - 28 * day).toISOString(),
    updatedAt: new Date(Date.now() - 24 * day).toISOString(),
  },
  {
    id: 'order-2',
    orderNumber: 'ORD-100202',
    userId: 'user-customer-02',
    customerName: 'Sarah Connor',
    customerEmail: 'sarah.connor@cyberdyne.com',
    status: 'DELIVERED',
    subtotal: 2648.99,
    taxAmount: 212.0,
    shippingAmount: 0,
    discountAmount: 100.0,
    totalAmount: 2760.99,
    currency: 'USD',
    paymentMethod: 'STRIPE',
    paymentStatus: 'PAID',
    transactionId: 'ch_3NrkX2LkdIwHu7ix08wFp102',
    shippingAddress: {
      addressLine1: '214 Desert Highway',
      city: 'Mojave',
      state: 'CA',
      postalCode: '93501',
      country: 'United States',
    },
    items: [
      {
        productId: 'prod-2',
        sku: 'LAPTOP-NOVA-16',
        title: 'NovaBook Pro 16" M3 Max Workstation',
        unitPrice: 2499.0,
        quantity: 1,
        totalPrice: 2499.0,
        imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
      },
      {
        productId: 'prod-5',
        sku: 'GAME-VORTEX-KB',
        title: 'Vortex RGB Mechanical Gaming Keyboard',
        unitPrice: 149.99,
        quantity: 1,
        totalPrice: 149.99,
        imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80',
      },
    ],
    createdAt: new Date(Date.now() - 25 * day).toISOString(),
    updatedAt: new Date(Date.now() - 20 * day).toISOString(),
  },
  {
    id: 'order-3',
    orderNumber: 'ORD-100203',
    userId: 'user-customer-03',
    customerName: 'Priya Natarajan',
    customerEmail: 'priya.natarajan@example.com',
    status: 'SHIPPED',
    subtotal: 799.0,
    taxAmount: 63.92,
    shippingAmount: 12.99,
    discountAmount: 0,
    totalAmount: 875.91,
    currency: 'USD',
    paymentMethod: 'PAYPAL',
    paymentStatus: 'PAID',
    transactionId: 'PAYID-MTG837492103',
    shippingAddress: {
      addressLine1: '88 Lakeshore Drive',
      city: 'Chicago',
      state: 'IL',
      postalCode: '60601',
      country: 'United States',
    },
    items: [
      {
        productId: 'prod-3',
        sku: 'WATCH-HORIZON-U',
        title: 'Titanium Horizon Smartwatch Ultra',
        unitPrice: 799.0,
        quantity: 1,
        totalPrice: 799.0,
        imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
      },
    ],
    createdAt: new Date(Date.now() - 9 * day).toISOString(),
    updatedAt: new Date(Date.now() - 2 * day).toISOString(),
  },
  {
    id: 'order-4',
    orderNumber: 'ORD-100204',
    userId: 'user-customer-01',
    customerName: 'Alex Morgan',
    customerEmail: 'customer@ecommerce.com',
    status: 'PROCESSING',
    subtotal: 189.99,
    taxAmount: 15.2,
    shippingAmount: 5.99,
    discountAmount: 0,
    totalAmount: 211.18,
    currency: 'USD',
    paymentMethod: 'STRIPE',
    paymentStatus: 'PAID',
    transactionId: 'ch_3NrkX2LkdIwHu7ix08wFp104',
    shippingAddress: {
      addressLine1: '742 Evergreen Terrace',
      city: 'Springfield',
      state: 'OR',
      postalCode: '97477',
      country: 'United States',
    },
    items: [
      {
        productId: 'prod-4',
        sku: 'AUDIO-PULSE-02',
        title: 'Pulse Studio Wireless Earbuds',
        unitPrice: 189.99,
        quantity: 1,
        totalPrice: 189.99,
        imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80',
      },
    ],
    createdAt: new Date(Date.now() - 4 * day - 3 * hour).toISOString(),
    updatedAt: new Date(Date.now() - 1 * day).toISOString(),
  },
  {
    id: 'order-5',
    orderNumber: 'ORD-100205',
    userId: 'user-customer-04',
    customerName: 'Derek Whitfield',
    customerEmail: 'derek.whitfield@example.com',
    status: 'PROCESSING',
    subtotal: 649.99,
    taxAmount: 52.0,
    shippingAmount: 0,
    discountAmount: 0,
    totalAmount: 701.99,
    currency: 'USD',
    paymentMethod: 'MOCK',
    paymentStatus: 'PAID',
    transactionId: 'MOCK-TXN-58231470',
    shippingAddress: {
      addressLine1: '19 Birchwood Lane',
      city: 'Portland',
      state: 'ME',
      postalCode: '04101',
      country: 'United States',
    },
    items: [
      {
        productId: 'prod-6',
        sku: 'MONITOR-LUMIX-27',
        title: 'Lumix Neo 4K 144Hz IPS Monitor 27"',
        unitPrice: 649.99,
        quantity: 1,
        totalPrice: 649.99,
        imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80',
      },
    ],
    createdAt: new Date(Date.now() - 3 * day - 6 * hour).toISOString(),
    updatedAt: new Date(Date.now() - 18 * hour).toISOString(),
  },
  {
    id: 'order-6',
    orderNumber: 'ORD-100206',
    userId: 'user-customer-05',
    customerName: 'Maria Gutierrez',
    customerEmail: 'maria.gutierrez@example.com',
    status: 'SHIPPED',
    subtotal: 339.98,
    taxAmount: 27.2,
    shippingAmount: 8.5,
    discountAmount: 20.0,
    totalAmount: 355.68,
    currency: 'USD',
    paymentMethod: 'PAYPAL',
    paymentStatus: 'PAID',
    transactionId: 'PAYID-MTG837492106',
    shippingAddress: {
      addressLine1: '4520 Sunset Boulevard',
      city: 'Miami',
      state: 'FL',
      postalCode: '33139',
      country: 'United States',
    },
    items: [
      {
        productId: 'prod-4',
        sku: 'AUDIO-PULSE-02',
        title: 'Pulse Studio Wireless Earbuds',
        unitPrice: 189.99,
        quantity: 1,
        totalPrice: 189.99,
        imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80',
      },
      {
        productId: 'prod-5',
        sku: 'GAME-VORTEX-KB',
        title: 'Vortex RGB Mechanical Gaming Keyboard',
        unitPrice: 149.99,
        quantity: 1,
        totalPrice: 149.99,
        imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80',
      },
    ],
    createdAt: new Date(Date.now() - 7 * day - 2 * hour).toISOString(),
    updatedAt: new Date(Date.now() - 3 * day).toISOString(),
  },
  {
    id: 'order-7',
    orderNumber: 'ORD-100207',
    userId: 'user-customer-02',
    customerName: 'Sarah Connor',
    customerEmail: 'sarah.connor@cyberdyne.com',
    status: 'PENDING',
    subtotal: 149.99,
    taxAmount: 12.0,
    shippingAmount: 5.99,
    discountAmount: 0,
    totalAmount: 167.98,
    currency: 'USD',
    paymentMethod: 'STRIPE',
    paymentStatus: 'PENDING',
    transactionId: 'ch_3NrkX2LkdIwHu7ix08wFp107',
    shippingAddress: {
      addressLine1: '214 Desert Highway',
      city: 'Mojave',
      state: 'CA',
      postalCode: '93501',
      country: 'United States',
    },
    items: [
      {
        productId: 'prod-5',
        sku: 'GAME-VORTEX-KB',
        title: 'Vortex RGB Mechanical Gaming Keyboard',
        unitPrice: 149.99,
        quantity: 1,
        totalPrice: 149.99,
        imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80',
      },
    ],
    createdAt: new Date(Date.now() - 5 * hour).toISOString(),
    updatedAt: new Date(Date.now() - 5 * hour).toISOString(),
  },
  {
    id: 'order-8',
    orderNumber: 'ORD-100208',
    userId: 'user-customer-03',
    customerName: 'Priya Natarajan',
    customerEmail: 'priya.natarajan@example.com',
    status: 'CONFIRMED',
    subtotal: 799.0,
    taxAmount: 63.92,
    shippingAmount: 0,
    discountAmount: 50.0,
    totalAmount: 812.92,
    currency: 'USD',
    paymentMethod: 'STRIPE',
    paymentStatus: 'PAID',
    transactionId: 'ch_3NrkX2LkdIwHu7ix08wFp108',
    shippingAddress: {
      addressLine1: '88 Lakeshore Drive',
      city: 'Chicago',
      state: 'IL',
      postalCode: '60601',
      country: 'United States',
    },
    items: [
      {
        productId: 'prod-3',
        sku: 'WATCH-HORIZON-U',
        title: 'Titanium Horizon Smartwatch Ultra',
        unitPrice: 799.0,
        quantity: 1,
        totalPrice: 799.0,
        imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
      },
    ],
    createdAt: new Date(Date.now() - 1 * day - 4 * hour).toISOString(),
    updatedAt: new Date(Date.now() - 20 * hour).toISOString(),
  },
  {
    id: 'order-9',
    orderNumber: 'ORD-100209',
    userId: 'user-customer-01',
    customerName: 'Alex Morgan',
    customerEmail: 'customer@ecommerce.com',
    status: 'CANCELLED',
    subtotal: 839.98,
    taxAmount: 56.0,
    shippingAmount: 0,
    discountAmount: 0,
    totalAmount: 895.98,
    currency: 'USD',
    paymentMethod: 'PAYPAL',
    paymentStatus: 'REFUNDED',
    transactionId: 'PAYID-MTG837492109',
    shippingAddress: {
      addressLine1: '742 Evergreen Terrace',
      city: 'Springfield',
      state: 'OR',
      postalCode: '97477',
      country: 'United States',
    },
    items: [
      {
        productId: 'prod-4',
        sku: 'AUDIO-PULSE-02',
        title: 'Pulse Studio Wireless Earbuds',
        unitPrice: 189.99,
        quantity: 1,
        totalPrice: 189.99,
        imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80',
      },
      {
        productId: 'prod-6',
        sku: 'MONITOR-LUMIX-27',
        title: 'Lumix Neo 4K 144Hz IPS Monitor 27"',
        unitPrice: 649.99,
        quantity: 1,
        totalPrice: 649.99,
        imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80',
      },
    ],
    createdAt: new Date(Date.now() - 14 * day).toISOString(),
    updatedAt: new Date(Date.now() - 12 * day).toISOString(),
  },
  {
    id: 'order-10',
    orderNumber: 'ORD-100210',
    userId: 'user-customer-04',
    customerName: 'Derek Whitfield',
    customerEmail: 'derek.whitfield@example.com',
    status: 'DELIVERED',
    subtotal: 349.99,
    taxAmount: 28.0,
    shippingAmount: 0,
    discountAmount: 0,
    totalAmount: 377.99,
    currency: 'USD',
    paymentMethod: 'STRIPE',
    paymentStatus: 'PAID',
    transactionId: 'ch_3NrkX2LkdIwHu7ix08wFp110',
    shippingAddress: {
      addressLine1: '19 Birchwood Lane',
      city: 'Portland',
      state: 'ME',
      postalCode: '04101',
      country: 'United States',
    },
    items: [
      {
        productId: 'prod-1',
        sku: 'AUDIO-AURA-01',
        title: 'Aura Pro Wireless ANC Headphones',
        unitPrice: 349.99,
        quantity: 1,
        totalPrice: 349.99,
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
      },
    ],
    createdAt: new Date(Date.now() - 21 * day).toISOString(),
    updatedAt: new Date(Date.now() - 17 * day).toISOString(),
  },
  {
    id: 'order-11',
    orderNumber: 'ORD-100211',
    userId: 'user-customer-05',
    customerName: 'Maria Gutierrez',
    customerEmail: 'maria.gutierrez@example.com',
    status: 'PENDING',
    subtotal: 179.98,
    taxAmount: 14.4,
    shippingAmount: 5.99,
    discountAmount: 0,
    totalAmount: 200.37,
    currency: 'USD',
    paymentMethod: 'MOCK',
    paymentStatus: 'PENDING',
    transactionId: 'MOCK-TXN-58231471',
    shippingAddress: {
      addressLine1: '4520 Sunset Boulevard',
      city: 'Miami',
      state: 'FL',
      postalCode: '33139',
      country: 'United States',
    },
    items: [
      {
        productId: 'prod-5',
        sku: 'GAME-VORTEX-KB',
        title: 'Vortex RGB Mechanical Gaming Keyboard',
        unitPrice: 149.99,
        quantity: 1,
        totalPrice: 149.99,
      },
      {
        productId: 'prod-4',
        sku: 'AUDIO-PULSE-02',
        title: 'Pulse Studio Wireless Earbuds',
        unitPrice: 29.99,
        quantity: 1,
        totalPrice: 29.99,
      },
    ],
    createdAt: new Date(Date.now() - 2 * hour).toISOString(),
    updatedAt: new Date(Date.now() - 2 * hour).toISOString(),
  },
  {
    id: 'order-12',
    orderNumber: 'ORD-100212',
    userId: 'user-customer-02',
    customerName: 'Sarah Connor',
    customerEmail: 'sarah.connor@cyberdyne.com',
    status: 'DELIVERED',
    subtotal: 189.99,
    taxAmount: 15.2,
    shippingAmount: 0,
    discountAmount: 0,
    totalAmount: 205.19,
    currency: 'USD',
    paymentMethod: 'STRIPE',
    paymentStatus: 'PAID',
    transactionId: 'ch_3NrkX2LkdIwHu7ix08wFp112',
    shippingAddress: {
      addressLine1: '214 Desert Highway',
      city: 'Mojave',
      state: 'CA',
      postalCode: '93501',
      country: 'United States',
    },
    items: [
      {
        productId: 'prod-4',
        sku: 'AUDIO-PULSE-02',
        title: 'Pulse Studio Wireless Earbuds',
        unitPrice: 189.99,
        quantity: 1,
        totalPrice: 189.99,
        imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80',
      },
    ],
    createdAt: new Date(Date.now() - 30 * day).toISOString(),
    updatedAt: new Date(Date.now() - 27 * day).toISOString(),
  },
]
